//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(QualitativeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CriterionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.monash.edu/MADAM")]
[System.Xml.Serialization.XmlRootAttribute("Mark", Namespace="http://www.monash.edu/MADAM", IsNullable=false)]
public abstract partial class MarkType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private string descriptionField;
    
    private string markerInstructionField;
    
    private string labelField;
    
    private bool groupField;
    
    private bool groupFieldSpecified;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
            System.Diagnostics.Debug.WriteLine("MarkType: Name changed");
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
            this.RaisePropertyChanged("Description");
        }
    }
    
    /// <remarks/>
    public string MarkerInstruction {
        get {
            return this.markerInstructionField;
        }
        set {
            this.markerInstructionField = value;
            this.RaisePropertyChanged("MarkerInstruction");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
            this.RaisePropertyChanged("label");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
            this.RaisePropertyChanged("group");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool groupSpecified {
        get {
            return this.groupFieldSpecified;
        }
        set {
            this.groupFieldSpecified = value;
            this.RaisePropertyChanged("groupSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.monash.edu/MADAM")]
public partial class CriterionType : MarkType {
    
    private string[] scaleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Level", IsNullable=false)]
    public string[] Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
            this.RaisePropertyChanged("Scale");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.monash.edu/MADAM")]
[System.Xml.Serialization.XmlRootAttribute("QTask", Namespace="http://www.monash.edu/MADAM", IsNullable=false)]
public partial class QualitativeType : MarkType {
    
    private QualitativeType[] subtasksField;
    
    private CriterionType[] criteriaField;
    
    private string[] scaleField;
    
    private bool hasCommentField;
    
    private bool hasCommentFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("QTask", IsNullable=false)]
    public QualitativeType[] Subtasks {
        get {
            return this.subtasksField;
        }
        set {
            this.subtasksField = value;
            this.RaisePropertyChanged("Subtasks");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Criterion", IsNullable=false)]
    public CriterionType[] Criteria {
        get {
            return this.criteriaField;
        }
        set {
            this.criteriaField = value;
            this.RaisePropertyChanged("Criteria");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Level", IsNullable=false)]
    public string[] Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
            this.RaisePropertyChanged("Scale");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hasComment {
        get {
            return this.hasCommentField;
        }
        set {
            this.hasCommentField = value;
            this.RaisePropertyChanged("hasComment");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hasCommentSpecified {
        get {
            return this.hasCommentFieldSpecified;
        }
        set {
            this.hasCommentFieldSpecified = value;
            this.RaisePropertyChanged("hasCommentSpecified");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.monash.edu/MADAM")]
[System.Xml.Serialization.XmlRootAttribute("Task", Namespace="http://www.monash.edu/MADAM", IsNullable=false)]
public partial class NumericType : MarkType {
    
    private CriterionType[] criteriaField;
    
    private MarkType[] subtasksField;
    
    private decimal maxMarkField;
    
    private bool maxMarkFieldSpecified;
    
    private decimal minMarkField;
    
    private bool minMarkFieldSpecified;
    
    private bool hasCommentField;
    
    private bool hasCommentFieldSpecified;
    
    private bool bonusField;
    
    private bool bonusFieldSpecified;
    
    private bool penaltyField;
    
    private bool penaltyFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Criterion", IsNullable=false)]
    public CriterionType[] Criteria {
        get {
            return this.criteriaField;
        }
        set {
            this.criteriaField = value;
            this.RaisePropertyChanged("Criteria");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Mark", IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("QTask", typeof(QualitativeType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Task", typeof(NumericType), IsNullable=false)]
    public MarkType[] Subtasks {
        get {
            return this.subtasksField;
        }
        set {
            this.subtasksField = value;
            this.RaisePropertyChanged("Subtasks");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxMark {
        get {
            return this.maxMarkField;
        }
        set {
            this.maxMarkField = value;
            this.RaisePropertyChanged("maxMark");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxMarkSpecified {
        get {
            return this.maxMarkFieldSpecified;
        }
        set {
            this.maxMarkFieldSpecified = value;
            this.RaisePropertyChanged("maxMarkSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal minMark {
        get {
            return this.minMarkField;
        }
        set {
            this.minMarkField = value;
            this.RaisePropertyChanged("minMark");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minMarkSpecified {
        get {
            return this.minMarkFieldSpecified;
        }
        set {
            this.minMarkFieldSpecified = value;
            this.RaisePropertyChanged("minMarkSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hasComment {
        get {
            return this.hasCommentField;
        }
        set {
            this.hasCommentField = value;
            this.RaisePropertyChanged("hasComment");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hasCommentSpecified {
        get {
            return this.hasCommentFieldSpecified;
        }
        set {
            this.hasCommentFieldSpecified = value;
            this.RaisePropertyChanged("hasCommentSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool bonus {
        get {
            return this.bonusField;
        }
        set {
            this.bonusField = value;
            this.RaisePropertyChanged("bonus");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bonusSpecified {
        get {
            return this.bonusFieldSpecified;
        }
        set {
            this.bonusFieldSpecified = value;
            this.RaisePropertyChanged("bonusSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool penalty {
        get {
            return this.penaltyField;
        }
        set {
            this.penaltyField = value;
            this.RaisePropertyChanged("penalty");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool penaltySpecified {
        get {
            return this.penaltyFieldSpecified;
        }
        set {
            this.penaltyFieldSpecified = value;
            this.RaisePropertyChanged("penaltySpecified");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.monash.edu/MADAM")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.monash.edu/MADAM", IsNullable=false)]
public partial class Scheme : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string unitCodeField;
    
    private string activityNameField;
    
    private string preambleField;
    
    private string subtitleField;
    
    private MarkType[] tasksField;
    
    /// <remarks/>
    public string UnitCode {
        get {
            return this.unitCodeField;
        }
        set {
            this.unitCodeField = value;
            this.RaisePropertyChanged("UnitCode");
        }
    }
    
    /// <remarks/>
    public string ActivityName {
        get {
            return this.activityNameField;
        }
        set {
            this.activityNameField = value;
            this.RaisePropertyChanged("ActivityName");
        }
    }
    
    /// <remarks/>
    public string Preamble {
        get {
            return this.preambleField;
        }
        set {
            this.preambleField = value;
            this.RaisePropertyChanged("Preamble");
        }
    }
    
    /// <remarks/>
    public string Subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
            this.RaisePropertyChanged("Subtitle");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Mark", IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("QTask", typeof(QualitativeType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Task", typeof(NumericType), IsNullable=false)]
    public MarkType[] Tasks {
        get {
            return this.tasksField;
        }
        set {
            this.tasksField = value;
            this.RaisePropertyChanged("Tasks");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
